name: dutch_railway
profile: dutch_railway
model-paths:
  - models
macro-paths:
  - macros
target-path: target
clean-targets:
  - target
  - dbt_packages
models:
  dutch_railway:
    +tags:
      - tier2
    staging:
      +materialized: view
      +tags:
        - tier1
      +group: analytics_engineering
    marts:
      +materialized: view # Change to table for BI performance
      +group: analytics_engineering
      +docs:
        node_color: '#800080'
    analytics:
      +materialized: view
      +group: business_intelligence
      +docs:
        node_color: '#ff1dce'

# on-run-end: >
#   -- depends_on: {{ ref('dim_station') }} {{ ref('fact_station_distance') }} {{
#   ref('dim_route') }} {{ ref('fact_disruption') }} {{ ref('fact_service_stop')
#   }}  {{ sync_to_postgres() }}